Fix undefined Rmult_lt_pos_pos lemma by replacing with Rmult_lt_0_compat
The lemma Rmult_lt_pos_pos was undefined in Coq's Reals library.
Replaced it with Rmult_lt_0_compat which has the same logical meaning:
forall r1 r2, 0 < r1 -> 0 < r2 -> 0 < r1 * r2

This fixes the compilation errors in:
- proofs/trinity/CorePhi.v:14
- proofs/trinity/AlphaPhi.v:27

Closes #3328